<?php require_once $_SERVER['DOCUMENT_ROOT'].'../../Connections/PGC.php' ?>
<?php 
error_reporting(0);
if (!isset($_SESSION)) {
  session_start();
}
require_once('pgc_check_login.php'); 
?>
<?php
function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

define('EST_OFFSET',4*3600);
$Landtime = date("h:i:s",TIME()-EST_OFFSET);


$updateSQL = sprintf("UPDATE pgc_flightsheet SET Landing=%s WHERE `Key`=%s",
                       GetSQLValueString($Landtime, "date"),
                       GetSQLValueString($_GET['recordID'], "int"));

  mysql_select_db($database_PGC, $PGC);
  $Result1 = mysql_query($updateSQL, $PGC) or die(mysql_error());
  
 
  
 $updateTime = sprintf("UPDATE pgc_flightsheet SET Time = TIME_TO_SEC(TIMEDIFF(Landing,Takeoff))/3600 WHERE Landing > Takeoff AND `Key`=%s",
                         GetSQLValueString($_GET['recordID'], "int"));

  mysql_select_db($database_PGC, $PGC);
  $Result2 = mysql_query($updateTime, $PGC) or die(mysql_error());
  
 $updateTime = sprintf("UPDATE pgc_flightsheet SET Time = (TIME_TO_SEC(TIMEDIFF(Landing,Takeoff)) + 60*60*12)/3600 WHERE Landing < Takeoff AND `Key`=%s",
                         GetSQLValueString($_GET['recordID'], "int"));

  mysql_select_db($database_PGC, $PGC);
  $Result2 = mysql_query($updateTime, $PGC) or die(mysql_error());
 
/*== Send Email ====*/

mysql_select_db($database_PGC, $PGC);
$query_Flightlog = sprintf("SELECT * FROM pgc_flightsheet WHERE `Key` = %s",
 GetSQLValueString($_GET['recordID'], "int"));
$Flightlog = mysql_query($query_Flightlog, $PGC) or die(mysql_error());
$row_Flightlog = mysql_fetch_assoc($Flightlog);
/*$totalRows_Flightlog = mysql_num_rows($Flightlog);*/

$intro = "\n" . "This message was generated by the PDP when your landing time was updated by the flight desk." . "\n\n". "You may receive additional updates when your tow altitude is updated ... or if additional changes are made to this log record.". "\n\n" . "Please email the Flight Log Administrator at flightlog.pgc@gmail.com or contact a BOD member if this data is not accurate."."\n\n";

        $emaillog = $intro .  "Source IP: " . $row_Flightlog['ip'] . "\n" . "Key: " . $row_Flightlog['Key'] . "\n" . "Date: " . $row_Flightlog['Date'] ."\n" . "Glider: " . $row_Flightlog['Glider'] ."\n" . "Pilot1: " . $row_Flightlog['Pilot1'] ."\n" . "Pilot2: " . $row_Flightlog['Pilot2'] ."\n" . "Takeoff: " . $row_Flightlog['Takeoff'] . "\n" . "Landing: " .  $Landtime ."\n" . "Duration: " . $row_Flightlog['Time'] ."\n".  "Tow Altitude: " . $row_Flightlog['Tow Altitude'] . "\n" . "Tow Plane: " . $row_Flightlog['Tow Plane'] . "\n" . "Tow Pilot: " . $row_Flightlog['Tow Pilot'] . "\n" . "Notes: " . $row_Flightlog['Notes'] . "\n\n " ;  
				 
	$webmaster = "support@pgcsoaring.org";
	$treasurer = "treasurer.pgc@gmail.com";
	$member = $row_Flightlog['email']; 
	 
	$to = $treasurer . "," . $webmaster. "," . $member;
	$to = $webmaster;
	$to = $webmaster. "," . $member;
		$subject = "PGC Flightlog - Landing Time Updated for Flight: " . $row_Flightlog['Key'] . " Updated By: " . $row_Flightlog['ip'] ;
	    $email = $_REQUEST['email'];
		$headers = "From: PGC Pilot Data Portal";
		//$headers = 'From: PDP@pgc.net' . "\r\n" .
		 $headers = 'From: support@pgcsoaring.org' . "\r\n" .
    'Reply-To:support@pgcsoaring.org' . "\r\n" .
    'X-Mailer: PHP/' . phpversion();

		$sent = mail($to, $subject,  $emaillog, $headers);
		
/*=======*/
   
 	  
  $insertGoTo = "pgc_flightlog_list_edit.php";
  if (isset($_SERVER['QUERY_STRING'])) {
    $insertGoTo .= (strpos($insertGoTo, '?')) ? "&" : "?";
    $insertGoTo .= $_SERVER['QUERY_STRING'];

  header(sprintf("Location: %s", $insertGoTo));

 }
 
 
?>

<?php
mysql_free_result($Flightlog);
?>



